### ISSUE TITLE
head problem

### ISSUE THREAD

**Issue by 0GURUGUAY** [mnesarco/MarzWorkbench#40]
I am drawing this telecaster head and get trouble to get it working.
I try your head and it is fine, so my problem is inside my drawing.
I put the contour, etc.... but no way. You can see it in red with Update draft. 
Where should I look for ? 
thank you.
Max

**Comment by 0GURUGUAY** [comment]
my svg
![telecaster_headstock001](https://github.com/user-attachments/assets/76b5eb37-d649-4144-b9c7-58c7b3f303ed)

**Comment by 0GURUGUAY** [comment]
my last try.... I tested a lot of thing but get every time this cut....
![Uploading Capture d’écran 2024-08-22 à 4.49.07 PM.png…]()

**Comment by mnesarco** [comment]
Unfortunately, the algorithm used to create the smooth transition does not work equally well with all possible head stock shapes. Some minimum distance is required from transition and nut, but it depends on the shape, it is a bit fussy.

First, your contour path is not closed, it must be a closed path:
![Selection_792](https://github.com/user-attachments/assets/475e57ce-b602-43ea-8895-a73f1c25c134)

Secord, for some reason your reference lines are actually curves, it should not be a problem but i replaced them for actual lines.
![Selection_794](https://github.com/user-attachments/assets/1723e429-7120-411e-919a-d5031ba506f2)

Telecaster headstock is a very problematic shape on the bottom side because it is too straight, the algorithm expect something a bit more distant from the center, it could generate an ugly connection surface there if the is no bump.
![Selection_793](https://github.com/user-attachments/assets/9e98d30d-cb7b-4a5f-8f2b-141a70e6da64)

Finally, the distance between the transition and the nut must be a bit larger, you have to experiment until yo get it working without being to difference from your original shape.

![Selection_795](https://github.com/user-attachments/assets/cb7a3a3d-1e96-4546-8ce0-19e00fb2f528)

This is an approximation:
![Selection_796](https://github.com/user-attachments/assets/26506a1c-156c-4260-a152-3121e92a877a)

And finally, the "fixed" svg file:


![guruguay-fixed](https://github.com/user-attachments/assets/b906d304-dc99-4019-b9d7-4e98cc3fcb5a)

**Comment by mnesarco** [comment]
I have to improve the algorithm to reduce the required distance from transition to nut.

**Comment by mnesarco** [comment]
I have added a small adjustment in 0.1.8, so your original file works now just closing the open path.

![guruguay](https://github.com/user-attachments/assets/14f00564-fd8f-4687-822b-edb3eb90d409)

**Comment by 0GURUGUAY** [comment]
update, working well, thank you, I appreciate your help.

**Comment by mnesarco** [comment]
Great!!
