### ISSUE TITLE
Bass guitars

### ISSUE THREAD

**Issue by TheArtizan** [mnesarco/MarzWorkbench#8]
I must say how brilliant your idea is - I would like to adapt to make 4 string through neck bass guitars. There seems to be no way of changing to 4 strings and the neck through it looks like that is the neck joint all the way from top to bottom om body. I must say how brilliant your idea is - I would like to adapt to make 4 string through neck bass guitars. There seems to be no way of changing to 4 strings and the neck through option, looks like that is the neck joint all the way from top to bottom om body. I realise you have created it for 6 string guitars are ther any pointers as to ho I can modify the code to allow 4 string basses, thank you for your time, all the best 25 seconds ago
@TheArtizan

**Comment by mnesarco** [comment]
To create a 4 strings neck just set 4 gauges instead of 6:

![image](https://user-images.githubusercontent.com/1087317/109912206-935a7c80-7c79-11eb-8f58-776f04edb97e.png)

Remove last two:

![image](https://user-images.githubusercontent.com/1087317/109912270-aff6b480-7c79-11eb-9a95-61cdf7ba9769.png)

Then set the string distance at nut and bridge:

![image](https://user-images.githubusercontent.com/1087317/109912366-e3394380-7c79-11eb-82d5-306a665c7b2a.png)

![image](https://user-images.githubusercontent.com/1087317/109912398-f64c1380-7c79-11eb-9840-2251ad9cc30e.png)


No code changes required.

**Comment by TheArtizan** [comment]
Many thanks that is so helpful
All the best
